on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri, clippy
          override: true
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Lint code
        run: cargo clippy
      - name: Run tests
        run: |
          cargo test --all
      - name: Run miri
        run: cargo +nightly miri test --all
